### ISSUE TITLE
Restore "Break" action

### ISSUE THREAD

**Issue by Zidane** [AlmuraDev/Almura#340]
Need to restore reading in break action to determine what happens when a block is broken.

2.0 Reference:
```
        break:
            enabled: true
            tools:
                none:
                    experience: 10-15
                    exhaustion-change: 5-10
                    drops:
                        almura\food\corn:
                            amount: 1-2
                            data: 2
                            bonus:
                                enabled: false
                                amount: 1-5
                                chance: 10-15
                almura\tools\diamond_sickle:
                    experience: 10-15
                    exhaustion-change: 5-10
                    drops:
                        almura\food\corn:
                            amount: 3-4
                            data: 2
                            bonus:
                                enabled: true
                                amount: 4-5
                                chance: 45-75
```
